# Generated by Django 3.2.6 on 2021-08-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='django_LMS/adminportal/default.png', upload_to=''),
        ),
    ]
