# Generated by Django 3.2.6 on 2021-08-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_about_info',
            field=models.TextField(default='Course info'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_learning_oucomes',
            field=models.TextField(default='Course learning outcomes'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_image',
            field=models.ImageField(default='django_LMS/static/adminportal/instructor.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='Instructor Name', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='intructor_designation',
            field=models.CharField(default='Instructor Designation', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='django_LMS/static/adminportal/default.png', upload_to=''),
        ),
    ]
