# Generated by Django 3.2.6 on 2021-08-30 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminportal', '0004_rename_intructor_designation_course_instructor_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users_registerd',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
