# Generated by Django 3.2.6 on 2021-08-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0005_course_users_registerd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users_registerd',
            new_name='users_registered',
        ),
    ]
